days/069-072-django-rest/demo/api/urls.py
from django.urls import path, include
from rest_framework_swagger.views import get_swagger_view

from .views import QuoteList, QuoteDetail

schema_view = get_swagger_view(title='PyBites Quotes API')

urlpatterns = [
    path('', QuoteList.as_view()),
    path('<int:pk>', QuoteDetail.as_view()),
    path('api-auth/', include('rest_framework.urls')),
    path('docs/', schema_view),
]

days/069-072-django-rest/demo/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('quotes.urls')),
    path('my-backend/', admin.site.urls),
    path(r'accounts/', include('django_registration.backends.activation.urls')),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path(r'api/', include('api.urls')),
]

days/069-072-django-rest/demo/quotes/urls.py
from django.urls import path

from . import views

app_name = 'quotes'
urlpatterns = [
    path('', views.quote_list, name='quote_list'),
    path('<int:pk>', views.quote_detail, name='quote_detail'),
    path('new', views.quote_new, name='quote_new'),
    path('edit/<int:pk>', views.quote_edit, name='quote_edit'),
    path('delete/<int:pk>', views.quote_delete, name='quote_delete'),
]

days/069-072-django-rest/demo/api/models.py
from django.db import models

# Create your models here.

days/069-072-django-rest/demo/quotes/models.py
from django.contrib.auth.models import User
from django.db import models


class Quote(models.Model):
    quote = models.TextField()
    author = models.CharField(max_length=100)
    source = models.URLField(blank=True, null=True)
    cover = models.URLField(blank=True, null=True)
    added = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             blank=True, null=True)

    def __str__(self):
        return f'{self.quote} - {self.author} (submitted by {self.user})'

    class Meta:
        ordering = ['-added']

days/069-072-django-rest/demo/quotes/forms.py
from django.forms import ModelForm

from .models import Quote


class QuoteForm(ModelForm):
    class Meta:
        model = Quote
        exclude = ('user',)

days/069-072-django-rest/demo/api/views.py
from rest_framework import generics

from quotes.models import Quote
from .serializers import QuoteSerializer
from .permissions import IsOwnerOrReadOnly


class QuoteList(generics.ListCreateAPIView):
    """
    get:
    Return a list of all quotes in the DB.

    post:
    Create an awesome new quote.
    """
    queryset = Quote.objects.all()
    serializer_class = QuoteSerializer


class QuoteDetail(generics.RetrieveUpdateDestroyAPIView):
    """
    get:
    Return an individual quote.

    put:
    Update an existing quote.

    delete:
    Delete a single quote.
    """
    permission_classes = (IsOwnerOrReadOnly, )
    queryset = Quote.objects.all()
    serializer_class = QuoteSerializer

days/069-072-django-rest/demo/quotes/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from .models import Quote
from .forms import QuoteForm


def quote_list(request):
    quotes = Quote.objects.all()
    return render(request, 'quotes/quote_list.html', {'quotes': quotes})


def quote_detail(request, pk):
    quote = get_object_or_404(Quote, pk=pk)
    return render(request, 'quotes/quote_detail.html', {'quote': quote})


@login_required
def quote_new(request):
    form = QuoteForm(request.POST or None)

    if form.is_valid():
        form = form.save(commit=False)
        form.user = request.user
        form.save()
        messages.success(request, 'Added quote')
        return redirect('quotes:quote_list')

    return render(request, 'quotes/quote_form.html', {'form': form})


@login_required
def quote_edit(request, pk):
    quote = get_object_or_404(Quote, pk=pk, user=request.user)
    form = QuoteForm(request.POST or None, instance=quote)

    if form.is_valid():
        form = form.save(commit=False)
        form.user = request.user
        form.save()
        messages.success(request, 'Updated quote')
        return redirect('quotes:quote_list')

    return render(request, 'quotes/quote_form.html', {'quote': quote,
                                                      'form': form})


@login_required
def quote_delete(request, pk):
    quote = get_object_or_404(Quote, pk=pk, user=request.user)

    if request.method == 'POST':
        quote.delete()
        messages.success(request, 'Deleted quote')
        return redirect('quotes:quote_list')

    return render(request, 'quotes/quote_confirm_delete.html', {'quote': quote})

days/069-072-django-rest/demo/mysite/templates/base.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PyBites Quotes</title>
    <link href="//cdn.muicss.com/mui-0.9.40/css/mui.min.css" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <script src="//cdn.muicss.com/mui-0.9.40/js/mui.min.js"></script>
  </head>
  <body
    {% if quote and quote.cover %}
      style="background: url({{ quote.cover }}) no-repeat center center fixed; background-size:cover;"
    {% endif %}
  >
    <header class="mui-appbar mui--z1">
      <div class="mui-container">
        <table>
          <tr class="mui--appbar-height">
            <td class="mui--text-title"><a id="pageTitle" href="{% url "quotes:quote_list" %}">PyBites Quotes</a></td>
            <td class="mui--text-right">
              <ul class="mui-list--inline mui--text-body2">
                <li><a href="#">About</a></li>
                {% if request.user.is_authenticated %}
                  <li>Welcome back {{ request.user.username }}, <a href="{% url 'logout' %}">logout</a></li>
                {% else %}
                  <li><a href="{% url 'login' %}">Login to add quotes</a></li>
                {% endif %}
              </ul>
            </td>
          </tr>
        </table>
      </div>

    </header>

    <div id="content-wrapper"
      {% if quote and quote.cover %}
        style="background: #fff; color: #000; opacity: 0.8;"
      {% endif %}
    >

      <div class="mui--appbar-height"></div>

      <div class="mui-container">
        <br><br>

        <div id="messages">
          {% for message in messages %}
            <p style="color: {% if message.tags == 'success' %}green{% elif message.tags == 'error' %}red{% endif %}">
              {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
            </p>
          {% endfor %}
        </div>

        {% block content %}{% endblock %}
      </div>

    </div><!-- end content-wrapper -->

    <footer>
      <div class="mui-container mui--text-center">
        Made with ♥ by <a href="https://www.muicss.com">MUICSS</a>
      </div>
    </footer>

  </body>
</html>

days/069-072-django-rest/demo/quotes/templates/quotes/quote_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

  <h1 class="mui--text-display1">Confirm Delete Quote</h1>

  <form method="post">
    {% csrf_token %}
    <blockquote>{{ quote.quote }}</blockquote>
    <p>Are you sure you want to delete this quote?</p>
    <input class="mui-btn mui-btn--danger" type="submit" value="Delete" />
    <a class="mui-btn mui-btn--raised" href="{% url "quotes:quote_list" %}">Go Back</a>
  </form>

{% endblock %}

days/069-072-django-rest/demo/quotes/templates/quotes/quote_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}

  <div class="mui-panel">
    <div class="mui-container">
      <blockquote>{{ quote.quote }}</blockquote>
      <cite>- {{ quote.author }}</cite>
    </div>
  </div>

  <div class="mui-container">
    {% if quote.user == request.user %}
      <a class="mui-btn mui-btn--primary" href="{% url "quotes:quote_edit" quote.id %}">Edit</a>
    {% endif %}
    <a class="mui-btn mui-btn--raised" href="{% url "quotes:quote_list" %}">Go Back</a>
  </div>

{% endblock %}

days/069-072-django-rest/demo/quotes/templates/quotes/quote_form.html
{% extends 'base.html' %}

{% block content %}

  <h1 class="mui--text-display1">{% if quote %}Edit{% else %}New{% endif %} Quote</h1>
  <form method="post">
    {% csrf_token %}

    {% for field in form %}
      <td>
        <div class="mui-textfield">
            {{ field.errors }}
            <p>{{ field.label_tag }}</p>
            {{ field }}
            {% if field.help_text %}
              <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
      </td>
    {% endfor %}

    <input class="mui-btn mui-btn--primary" type="submit" value="{% if quote %}Edit{% else %}New{% endif %}" />
    <a class="mui-btn mui-btn--raised" href="{% url "quotes:quote_list" %}">Go Back</a>
  </form>

{% endblock %}

days/069-072-django-rest/demo/quotes/templates/quotes/quote_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}

  <table class="mui-table mui-table--bordered">
    <thead>
        <tr>
          <th>Quote</th>
          <th>Author</th>
          <th>Added</th>
          <th colspan="2">Edit Quote</th>
        </tr>
    </thead>
    <tbody>
        <!-- for class based views rename this queryset to quote_list -->
        {% for quote in quotes %}
        <tr>
          <td><a href="{% url "quotes:quote_detail" quote.id %}">{{ quote.quote }}</a></td>
          <td>{{ quote.author }}</td>
          <td>{{ quote.added|timesince }} ago by {{ quote.user }}</td>
          {% if quote.user == request.user %}
            <td><a class="mui-bDeleted mui-btn--small mui-btn--flat mui-btn--primary" href="{% url "quotes:quote_edit" quote.id %}">Edit</a></td>
            <td><a class="mui-btn mui-btn--small mui-btn--flat mui-btn--danger" href="{% url "quotes:quote_delete" quote.id %}">Delete</a></td>
          {% else %}
            <td colspan="2"></td>
          {% endif %}
        </tr>
        {% endfor %}
    </tbody>
  </table>

  <div class="mui-container">
    {% if request.user.is_authenticated %}
      <a class="mui-btn mui-btn--primary" href="{% url "quotes:quote_new" %}">Add a quote</a>
    {% else %}
      <a class="mui-btn mui-btn--primary" href="{% url "login" %}">Login to add quotes</a>
    {% endif %}
      
  </div>

{% endblock %}